version: '3'
services:
  proxy:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.mega65.acme.email=webmaster@mega65.org"
      - "--certificatesresolvers.mega65.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.mega65.acme.httpchallenge=true"
      - "--certificatesresolvers.mega65.acme.httpchallenge.entrypoint=web"
    networks:
      - dmz
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/letsencrypt

networks:
  dmz:
    external: true

volumes:
  acme:
