version: '3'
services:
  jenkins:
    image: localjenkins
    build:
      context: .
      args:
        JENKINS_VERSION: 2.397
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - dmz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/var/jenkins_home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins-jenkins.rule=( Host(`builder.mega65.org`) || Host(`artifact.mega65.org`) )"
      - "traefik.http.routers.jenkins-jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins-jenkins.tls.certresolver=mega65"
      - "traefik.http.services.jenkins-jenkins.loadbalancer.server.port=8080"

networks:
  dmz:
    external: true

volumes:
  data:
